---
engines:
  spotbugs:
    modules:
      - classesDirectories: [ "core/base/build/classes" ]
        sourceDirectories:  [ "core/base/src/main" ]
      - classesDirectories: [ "core/contract/build/classes" ]
        sourceDirectories:  [ "core/contract/main" ]