version: "3.8"

services:

  #####
  # Setup for Metrics with Azure Application Insights.
  # Connection string must be defined in .env file
  #####

  consumerA:
    profiles: ["azure"]
    image: openjdk:11-jre-slim-buster
    deploy:
      replicas: 2
    environment:
      APPLICATIONINSIGHTS_CONNECTION_STRING: $APPLICATIONINSIGHTS_CONNECTION_STRING
      APPLICATIONINSIGHTS_ROLE_NAME: consumer
      edc.api.control.auth.apikey.value: password
      ids.webhook.address: http://consumerA:8181
    volumes:
      - .:/app
    entrypoint: java -javaagent:/app/applicationinsights-agent-3.2.4.jar -jar /app/samples/04-file-transfer/consumer/build/libs/consumer.jar

  providerA:
    profiles: ["azure"]
    image: openjdk:11-jre-slim-buster
    deploy:
      replicas: 2
    environment:
      APPLICATIONINSIGHTS_CONNECTION_STRING: $APPLICATIONINSIGHTS_CONNECTION_STRING
      APPLICATIONINSIGHTS_ROLE_NAME: provider
      edc.samples.04.asset.path: /tmp
      ids.webhook.address: http://providerA:8181
    volumes:
      - .:/app
    entrypoint: java -javaagent:/app/applicationinsights-agent-3.2.4.jar -jar /app/samples/04-file-transfer/provider/build/libs/provider.jar

  connector-integration-testA:
    profiles: ["azure"]
    image: adoptopenjdk:11-jre-hotspot
    command: /connector-integration-test.sh providerA:8181 consumerA:8181
    volumes:
      - ./samples:/samples
      - ./connector-integration-test.sh:/connector-integration-test.sh

  #####
  # Setup for Metrics with Prometheus.
  # Web interface can be accessed at http://localhost:9090
  #####

  consumerP:
    profiles: ["prometheus"]
    image: openjdk:11-jre-slim-buster
    deploy:
      replicas: 2
    environment:
      edc.api.control.auth.apikey.value: password
      ids.webhook.address: http://consumerP:8181
    volumes:
      - .:/app
    entrypoint: java -jar /app/samples/04-file-transfer/consumer/build/libs/consumer.jar

  providerP:
    profiles: ["prometheus"]
    image: openjdk:11-jre-slim-buster
    deploy:
      replicas: 2
    environment:
      edc.samples.04.asset.path: /tmp
      ids.webhook.address: http://providerP:8181
    volumes:
      - .:/app
    entrypoint: java -jar /app/samples/04-file-transfer/provider/build/libs/provider.jar

  connector-integration-testP:
    profiles: ["prometheus"]
    image: adoptopenjdk:11-jre-hotspot
    command: /connector-integration-test.sh providerP:8181 consumerP:8181
    volumes:
      - ./samples:/samples
      - ./connector-integration-test.sh:/connector-integration-test.sh

  prometheus:
    profiles: ["prometheus"]
    image: prom/prometheus:v2.30.3
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - 9090:9090
