image:
  repository: algattikacr.azurecr.io/provider
  tag: latest
  pullPolicy: Always
ingress:
  enabled: true
  pathType: Prefix
  hostname: algattikaks.northeurope.cloudapp.azure.com
  path: /provider/(.*)
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
  ingressClassName: nginx
edc:
  env:
    ids.webhook.address: http://algattikaks.northeurope.cloudapp.azure.com/provider
    edc.samples.04.asset.path: /tmp
