apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-edc
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-edc
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.container.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-edc