apiVersion: v1
kind: Service
metadata:
  name: edc
  labels:
    app.kubernetes.io/name: edc
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8181
      protocol: TCP
  selector:
    app.kubernetes.io/name: edc