apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edc.fullname" . }}-envvars
data:
  {{- range $envName, $value := .Values.edc.env }}
  {{ $envName | quote }}: {{ $value | quote }}
  {{- end }}
