image:
  repository: consumer
  tag: latest
  pullPolicy: Never
container:
  port: 8181
ingress:
  className: nginx
  prefix: /edcconsumer
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
  nameSuffix: "edcingress"