image:
  repository: <container-registry-repository>
  tag: <image-tag>
  pullPolicy: Always # Should be set to `Never` if using a local image
container:
  port: <edc-port>
ingress:
  host: <host>
  className: <ingress-controller-ingress-class>
  prefix: <ingress-path-prefix>