name: Minikube test
on:
  push:
    branches:
      - main
      - 'spike/432'

jobs:
  deploy_to_minikube:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
      - uses: actions/checkout@v2
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Try the cluster
        run: kubectl get pods -A
      - name: Build image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build --build-arg CONNECTOR_NAME=consumer --build-arg CONNECTOR_ADDRESS=localhost:9191 -f samples/04-file-transfer/Dockerfile . -t consumer
          docker build --build-arg CONNECTOR_NAME=provider --build-arg CONNECTOR_ADDRESS=localhost:8181 -f samples/04-file-transfer/Dockerfile . -t provider
          echo -n "verifying images:"
          docker images
      - name: Deploy to minikube
        run: |
          helm install r1 helm --set image.repository="" --set image.tag="" \
            --set ingress.prefix=/edcconsumer --set image.pullPolicy="Never" \
            --set container.port=8181 --set ingress.host=localhost --set ingress.className=nginx \
            -n consumer-namespace --create-namespace

      - name: Test
        run: |
          minikube service list
          kubectl get pods --all-namespaces
          kubectl get pods -n consumer-namespace
          kubectl logs edc-0 -n consumer-namespace
          minikube service discover --url