name: Minikube test
on:
  push:
    branches:
      - main
      - 'spike/432'
      - 'spike/432-minikube-test'

jobs:
  deploy_to_minikube:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
      - uses: actions/checkout@v2
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Try the cluster
        run: kubectl get pods -A
      - name: Build image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build --build-arg CONNECTOR_NAME=provider --build-arg CONNECTOR_ADDRESS=localhost:8181 -f samples/04-file-transfer/Dockerfile . -t provider:latest
          echo -n "verifying images:"
          docker images
      - name: Deploy to minikube
        run: |
          helm install r1 helm --debug --set image.repository="provider" --set image.tag="latest" \
            --set ingress.prefix=/edcprovider --set image.pullPolicy="Never" \
            --set container.port=8181 --set ingress.host=localhost --set ingress.className=nginx \
            -n provider-namespace --create-namespace
          sleep 4m
          kubectl get events

      - name: Test
        run: |
          minikube service list
          kubectl get pods --all-namespaces
          kubectl describe pod edc-0 -n provider-namespace
          kubectl wait --for=condition=ready pod edc-0 -n provider-namespace
          kubectl describe pod edc-0 -n provider-namespace
          minikube service discover --url
          kubectl logs edc-0 -n provider-namespace